# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OpenGL_config = debug

else ifeq ($(config),release)
  OpenGL_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := OpenGL

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OpenGL:
ifneq (,$(OpenGL_config))
	@echo "==== Building OpenGL ($(OpenGL_config)) ===="
	@${MAKE} --no-print-directory -C . -f OpenGL.make config=$(OpenGL_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f OpenGL.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OpenGL"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"